{
  try {
    return run.run();
  }
 catch (  Throwable throwable) {
    throw new AssertionError();
  }
}
