{
  try {
    doTest(newName);
  }
 catch (  Exception e) {
    assertEquals(message,e.getMessage());
    return;
  }
  fail("No exception was thrown");
}
