{
  final Throwable cause=exception.getCause();
  if (cause instanceof VagrantNotStartedException) {
    return new PyExecutionException("Vagrant instance is down",command,args,"","",0,ImmutableList.of(new LaunchVagrantFix(((VagrantNotStartedException)cause).getVagrantFolder(),((VagrantNotStartedException)cause).getMachineName())));
  }
  return exception;
}
