{
  if (!myFuture.setException(t)) {
    throw new Error("already excepted");
  }
}
